In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/gdrive/')

Mounted at /gdrive/

In [3]:
# Instala a biblioteca gdown para baixar arquivos do Google Drive
!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.19.1)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2025.8.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [ ]:
#Região Norte

# ID do arquivo do Google Drive
file_id_norte = '1vTvM-jwd_ot0hTqoKjKZj7zOig_k_FWy'
# Nome do arquivo para salvar no Colab
file_name_norte = 'regiao_Norte.csv'
file_name1_norte = 'regiao_norte'
# Baixa o arquivo do Google Drive
!gdown --id {file_id_norte} -O {file_name_norte}

# Carrega o arquivo de entrada usando pd.read_csv
df = pd.read_csv(file_name_norte)

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From (original): https://drive.google.com/uc?id=1vTvM-jwd_ot0hTqoKjKZj7zOig_k_FWy
From (redirected): https://drive.google.com/uc?id=1vTvM-jwd_ot0hTqoKjKZj7zOig_k_FWy&confirm=t&uuid=2f2e37e0-0fd0-44e6-870c-e88c6eef01d0
To: /content/regiao_Norte.csv
100% 1.81G/1.81G [00:16<00:00, 110MB/s]

In [ ]:
#Estado Amazonas

# ID do arquivo do Google Drive
file_id_amazonas = '15IQDhqSzHH7DUhGdzoDjVIidT_DG4DzN'
# Nome do arquivo para salvar no Colab
file_name_amazonas = 'estado_Amazonas.csv'
file_name1_amazonas = 'estado_amazonas'
# Baixa o arquivo do Google Drive
!gdown --id {file_id_norte} -O {file_name_norte}

# Carrega o arquivo de entrada usando pd.read_csv
df = pd.read_csv(file_name_amazonas)

FileNotFoundError: [Errno 2] No such file or directory: 'estado_Amazonas.csv'

In [4]:
#Região Nordeste

# ID do arquivo do Google Drive
file_id_nordeste = '1QmmkLawPbosOLEaO_YWCQvOn4_Y-Q4Ec'
# Nome do arquivo para salvar no Colab
file_name_nordeste = 'regiao_Nordeste.csv'
file_name1_nordeste = 'regiao_nordeste'
# Baixa o arquivo do Google Drive
!gdown --id {file_id_nordeste} -O {file_name_nordeste}

# Carrega o arquivo de entrada usando pd.read_csv
df = pd.read_csv(file_name_nordeste)

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Failed to retrieve file url:

	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1QmmkLawPbosOLEaO_YWCQvOn4_Y-Q4Ec

but Gdown can't. Please check connections and permissions.

FileNotFoundError: [Errno 2] No such file or directory: 'regiao_Nordeste.csv'

In [ ]:
#Região Centro_Oeste

# ID do arquivo do Google Drive
file_id_centro_oeste = '1x-2hQ1btEXn_eZvM9PAslPt09FoZV--V'
# Nome do arquivo para salvar no Colab
file_name_centro_oeste = 'regiao_Centro_Oeste.csv'
file_name1_centro_oeste = 'regiao_centro_oeste'
# Baixa o arquivo do Google Drive
!gdown --id {file_id_centro_oeste} -O {file_name_centro_oeste}

# Carrega o arquivo de entrada usando pd.read_csv
df = pd.read_csv(file_name_centro_oeste)

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Failed to retrieve file url:

	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1x-2hQ1btEXn_eZvM9PAslPt09FoZV--V

but Gdown can't. Please check connections and permissions.

FileNotFoundError: [Errno 2] No such file or directory: 'regiao_Centro_Oeste.csv'

In [5]:
#Região Sudeste

# ID do arquivo do Google Drive
file_id_sudeste = '1OMTpDu8-Ie8R0SwzemzXZ9bOFD4ljWQ1'
# Nome do arquivo para salvar no Colab
file_name_sudeste = 'regiao_Sudeste.csv'
file_name1_sudeste = 'regiao_sudeste'
# Baixa o arquivo do Google Drive
!gdown --id {file_id_sudeste} -O {file_name_sudeste}

# Carrega o arquivo de entrada usando pd.read_csv
df = pd.read_csv(file_name_sudeste)

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1OMTpDu8-Ie8R0SwzemzXZ9bOFD4ljWQ1

but Gdown can't. Please check connections and permissions.

FileNotFoundError: [Errno 2] No such file or directory: 'regiao_Sudeste.csv'

In [ ]:
#Região Sul

# ID do arquivo do Google Drive
file_id_sul = '1eH2lZrdUcWMnBGdR62x5S-5ReKRUc3f5'
# Nome do arquivo para salvar no Colab
file_name_sul = 'regiao_Sul.csv'
file_name1_sul = 'regiao_sul'
# Baixa o arquivo do Google Drive
!gdown --id {file_id_sul} -O {file_name_sul}

# Carrega o arquivo de entrada usando pd.read_csv
df = pd.read_csv(file_name_sul)

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(

In [ ]:
df_copy = df.copy()
df_copy

,spatial_id,spatial_geo_code,spatial_name,time_label,time_start_date,time_end_date,ADO. ALTURA X IDADE,ADO. IMC X IDADE,cd_ibge,classf,...,SISTEMA_ORIGEM_ACOMP,ST_PARTICIPA_ANDI,val_outras_rendas_memb,val_remuner_emprego_memb,val_renda_aposent_memb,val_renda_bruta_12_meses_memb,val_renda_doacao_memb,val_renda_pensao_alimen_memb,val_renda_seguro_desemp_memb,vlr_renda_media_fam
0,31805,1100015,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"{"""","""","""",""Estatura adequada para a idade"","""",...","{"""","""","""",Eutrofia,"""","""","""","""","""","""","""","""","""",...","{1100015,1100015,1100015,1100015,1100015,11000...","{3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3...",...,"{""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{0,"""",0,0,0,0,0,0,"""",0,0,0,"""",0,0,0,0,"""",0,"""",...","{0,"""",0,300,0,0,0,100,"""",0,0,0,"""",0,150,400,12...","{954,954,954,0,937,477,0,0,0,954,0,954,0,0,0,0...","{"""","""","""",10000,"""","""","""",1000,"""","""","""","""","""",""...","{0,"""",0,0,0,0,0,0,"""",0,0,0,"""",0,0,0,0,"""",0,"""",...","{0,0,0,0,0,0,0,0,75,0,0,0,0,0,0,0,0,0,0,0,0,0,...","{0,"""",0,0,0,0,0,0,"""",0,0,0,"""",0,0,0,0,"""",0,"""",...","{190,83,100,416,533,600,95,41,50,954,954,83,50..."
1,31810,1100023,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"{"""","""","""","""",""Estatura adequada para a idade"",...","{"""","""","""","""",""Risco de sobrepeso"","""","""","""","""",...","{1100023,1100023,1100023,1100023,1100023,11000...","{3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3...",...,"{""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{"""",0,0,0,"""","""",0,0,0,0,0,"""","""","""","""","""",0,"""",...","{"""",0,0,0,"""","""",0,0,0,0,0,"""","""","""","""","""",0,"""",...","{"""",0,0,880,0,0,937,0,0,937,0,0,0,0,0,0,0,0,0,...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{"""",150,0,0,"""","""",0,0,0,0,0,"""","""","""","""","""",0,""...","{"""",0,0,0,0,0,0,0,0,0,0,0,0,0,200,0,0,0,200,0,...","{"""",0,0,0,"""","""",0,0,0,0,0,"""","""","""","""","""",0,"""",...","{0,477,66,345,627,255,954,100,100,155,80,0,0,1..."
2,31815,1100031,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"{"""","""","""","""","""",""Estatura adequada para a idad...","{"""","""","""","""","""",Sobrepeso,"""","""","""","""","""","""",""""...","{1100031,1100031,1100031,1100031,1100031,11000...","{3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3...",...,"{""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{"""","""","""",0,"""",0,0,"""",0,"""",0,"""",0,0,0,0,0,0,20...","{"""","""","""",0,"""",200,0,"""",0,"""",700,"""",250,0,0,0,...","{0,0,0,880,0,0,0,0,0,0,0,0,0,0,0,0,0,880,0,0,0...","{"""","""","""","""","""",600,"""","""","""","""",8400,"""",3000,""...","{"""","""","""",0,"""",0,0,"""",0,"""",0,"""",0,50,0,0,0,0,0...","{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","{"""","""","""",0,"""",0,0,"""",0,"""",0,"""",0,0,0,0,0,0,0,...","{880,80,20,880,357,200,532,150,200,50,1908,954..."
3,31820,1100049,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"{"""","""","""","""","""","""","""","""",""Estatura adequada pa...","{"""","""","""","""","""","""","""","""",""Risco de sobrepeso"",...","{1100049,1100049,1100049,1100049,1100049,11000...","{3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3...",...,"{""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{0,0,0,"""",0,0,0,0,"""","""","""",0,"""","""","""",0,"""",0,0...","{0,954,0,"""",0,0,0,0,"""","""","""",0,"""","""","""",0,"""",9...","{0,954,0,0,937,0,937,0,0,0,0,0,0,0,0,954,0,0,0...","{"""",11448,"""","""","""","""","""","""","""","""","""","""","""","""",...","{0,0,0,"""",0,0,0,0,"""","""","""",0,"""","""","""",0,"""",0,0...","{0,0,0,0,0,0,0,0,0,0,0,300,0,0,0,0,0,0,0,0,0,0...","{0,0,0,"""",0,0,0,0,"""","""","""",0,"""","""","""",0,"""",0,0...","{193,83,636,100,175,433,568,937,288,440,137,37..."
4,31825,1100056,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{1100056,1100056,1100056,1100056,1100056,11000...","{3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3...",...,"{""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{0,0,0,"""",0,0,0,0,0,0,0,0,"""",0,0,0,0,0,0,"""",""""...","{0,954,0,"""",0,0,0,200,400,0,0,0,"""",900,0,200,0...","{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,788,0,0,0,0...","{"""",11448,"""","""","""","""","""",2400,4800,"""","""","""",""""...","{0,0,0,"""",0,100,250,0,0,0,0,200,"""",0,0,0,0,0,0...","{150,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","{0,0,0,"""",0,0,0,0,0,0,0,0,"""",0,0,0,0,0,0,"""",""""...","{160,300,468,60,83,477,937,150,1200,50,575,35,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,34030,1721208,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"{"""","""","""",""Estatura adequada para a idade"","""",...","{"""","""","""",Magreza,"""",Eutrofia,Eutrofia,"""","""",""...","{1721208,1721208,1721208,1721208,1721208,17212...","{3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3...",...,"{""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{100,600,100,"""","""","""",0,"""",0,"""",700,0,0,0,0,""""...","{0,0,0,"""","""","""",0,"""",0,"""",0,937,1365,0,0,"""",""""...","{0,0,0,0,0,0,0,954,0,0,0,0,0,0,937,0,0,0,0,0,0...","{"""","""","""","""","""","""","""","""","""","""","""",11244,16380,...","{0,0,0,"""","""","""",0,"""",0,"""",0,0,0,0,0,"""","""",0,0,...","{0,0,0,0,150,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","{0,0,0,"""","""","""",0,"""",0,"""",0,0,0,0,0,"""","""",0,0,...","{377,30,147,954,0,125,220,50,50,0,27,100,880,2..."
446,34035,1721257,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"{"""",""Estatura adequada para a idade"",""Estatura...","{"""",Eutrofia,Eutrofia,"""","""","""","""","""","""","""","""",...","{1721257,1721257,1721257,1721257,1721257,17212...","{3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3...",...,"{""E-SUS AB"",""E-SUS AB"",""AUXILIO BRASIL"",""E-SUS...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{0,"""",0,"""","""",0,"""","""",0,0,0,"""",0,0,0,"""",0,"""",""...","{0,"""",0,"""","""",0,"""","""",0,200,0,"""",0,0,0,"""",970,...","{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","{"""","""","""","""","""","""","""","""","""",2400,"""","""","""","""",""...","{0,"""",0,"""","""",0,"""","""",0,0,0,"""",0,0,0,"""",0,"""",""...","{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","{0,"""",0,"""","""",0,"""","""",0,0,0,"""",0,0,0,"""",0,"""",""...","{644,16,0,0,62,556,937,46,0,0,100,954,0,885,78..."
447,34040,1721307,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"{"""","""","""","""","""","""","""","""","""","""","""",""Estatura ad...","{"""","""","""","""","""","""","""","""","""","""","""",Eutrofia,"""",...","{1721307,1721307,1721307,1721307,1721307,17213...","{3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3...",...,"{""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{"""",0,"""","""",0,0,0,0,"""","""","""",0,"""","""",0,0,"""",0,...","{"""",0,"""","""",0,0,50,0,"""","""","""",0,"""","""",0,0,"""",2...","{0,0,0,0,0,0,0,880,0,0,0,0,0,0,0,880,0,0,0,0,0...","{"""","""","""","""","""","""",600,"""","""","""","""","""","""","""",""""...","{"""",0,"""","""",0,0,0,0,"""","""","""",0,"""","""",0,0,"""",0,...","{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","{"""",0,"""","""",0,0,0,0,"""","""","""",0,"""","""",0,0,"""",0,...","{19,2,150,468,0,11,954,724,250,477,0,306,0,0,3..."
448,34045,1722081,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{1722081,1722081,1722081,1722081,1722081,17220...","{3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3...",...,"{""E-SUS AB"",""AUXILIO BRASIL"",""AUXILIO BRASIL"",...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{0,"""",0,"""",0,0,0,0,0,0,0,"""","""",0,"""","""",0,0,0,""...","{0,"""",0,"""",200,0,0,0,0,0,1149,"""","""",200,"""","""",...","{0,0,0,0,0,0,0,0,937,880,0,0,0,0,0,0,0,954,0,0...","{"""","""","""","""",400,"""","""","""","""","""",13788,"""","""",24...","{0,"""",100,"""",0,50,150,0,0,0,0,"""","""",0,"""","""",0,...","{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","{0,"""",0,"""",0,0,0,0,0,0,0,"""","""",0,"""","""",0,0,0,""...","{4,66,100,20,62,50,300,200,420,8,937,37,416,47..."
449,34050,1722107,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"{"""","""",""Muito baixa estatura para idade"","""",""E...","{"""","""",Eutrofia,"""",Eutrofia,"""","""",Eutrofia,"""",...","{1722107,1722107,1722107,1722107,1722107,17221...","{3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3...",...,"{""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""E-SUS AB"",""...","{"""","""","""","""","""","""","""","""","""","""","""","""","""","""","""",...","{0,0,"""","""",0,"""",0,0,0,0,0,"""",0,0,0,0,0,0,0,0,0...","{0,120,"""","""",0,"""",0,600,0,500,150,"""",1500,200,...","{0,0,0,0,0,0,0,0,0,0,0,0,0,0,937,0,0,0,0,0,0,0...","{"""",720,"""","""","""","""","""",7200,"""",6000,1800,"""",60...","{0,0,"""","""",0,"""",0,0,0,0,0,"""",0,0,0,0,0,0,0,0,0...","{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","{0,0,"""","""",0,"""",0,0,0,0,0,"""",0,0,0,0,0,0,0,0,0...","{954,60,20,12,50,66,937,75,312,60,140,37,900,0..."

In [ ]:
df.ST_PARTICIPA_ANDI

0       {"","","","","","","","","","","","","","","",...
1       {"","","","","","","","","","","","","","","",...
2       {"","","","","","","","","","","","","","","",...
3       {"","","","","","","","","","","","","","","",...
4       {"","","","","","","","","","","","","","","",...
                              ...
1186    {"","","","","","","","","","","","","","","",...
1187    {"","","","","","","","","","","","","","","",...
1188    {"","","","","","","","","","","","","","","",...
1189    {"","","","","","","","","","","","","","","",...
1190    {"","","","","","","","","","","","","","","",...
Name: ST_PARTICIPA_ANDI, Length: 1191, dtype: object

In [ ]:
df.DS_IMC_PRE_GESTACIONAL

In [ ]:
df_copy.columns

Index(['spatial_id', 'spatial_geo_code', 'spatial_name', 'time_label',
       'time_start_date', 'time_end_date', 'ADO. ALTURA X IDADE',
       'ADO. IMC X IDADE', 'cd_ibge', 'classf',
       ...
       'SISTEMA_ORIGEM_ACOMP', 'ST_PARTICIPA_ANDI', 'val_outras_rendas_memb',
       'val_remuner_emprego_memb', 'val_renda_aposent_memb',
       'val_renda_bruta_12_meses_memb', 'val_renda_doacao_memb',
       'val_renda_pensao_alimen_memb', 'val_renda_seguro_desemp_memb',
       'vlr_renda_media_fam'],
      dtype='object', length=101)

In [ ]:
import re
import numpy as np

# Iterate through all columns and rows to clean strings that look like arrays
for col in df.columns:
    # Apply the cleaning only to columns that are of object type (likely containing strings)
    if df[col].dtype == 'object':
        # Remove espaços, colchetes, chaves, aspas
        df[col] = df[col].astype(str).apply(
            lambda x: re.sub(r'[\s\[\]{}"]', '', x) if isinstance(x, str) and re.match(r'[\s]*[{[]', x.strip()) else x
        )
        # Remover vírgulas duplicadas e bordas
        df[col] = df[col].astype(str).apply(
            lambda x: re.sub(r',+', ',', x).strip(',') if isinstance(x, str) else x
        )
        # 🔹 Converter "nan", "NaN", "None", "<NA>" em np.nan
        df[col] = df[col].replace(["nan", "NaN", "None", "<NA>", "null"], np.nan)

print("Removed spaces, specific characters, empty strings, and excluded nan-like strings.")
display(df)

Removed spaces, specific characters, empty strings, and excluded nan-like strings.

,spatial_id,spatial_geo_code,spatial_name,time_label,time_start_date,time_end_date,ADO. ALTURA X IDADE,ADO. IMC X IDADE,cd_ibge,classf,...,SISTEMA_ORIGEM_ACOMP,ST_PARTICIPA_ANDI,val_outras_rendas_memb,val_remuner_emprego_memb,val_renda_aposent_memb,val_renda_bruta_12_meses_memb,val_renda_doacao_memb,val_renda_pensao_alimen_memb,val_renda_seguro_desemp_memb,vlr_renda_media_fam
0,31805,1100015,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"Estaturaadequadaparaaidade,Estaturaadequadapar...","Eutrofia,Eutrofia,Eutrofia,Magreza,Eutrofia,Eu...","1100015,1100015,1100015,1100015,1100015,110001...","3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,...",...,"E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSA...",,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,300,0,0,0,100,0,0,0,0,150,400,120,0,880,0,...","954,954,954,0,937,477,0,0,0,954,0,954,0,0,0,0,...","10000,1000,1500,4800,1440,5280,1800,1200,7500,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,...","0,0,0,0,0,0,0,0,75,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","190,83,100,416,533,600,95,41,50,954,954,83,500..."
1,31810,1100023,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"Estaturaadequadaparaaidade,Estaturaadequadapar...","Riscodesobrepeso,Sobrepeso,Eutrofia,Riscodesob...","1100023,1100023,1100023,1100023,1100023,110002...","3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,...",...,"E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSA...",,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,100,1298,0,360,1200,0,1000...","0,0,880,0,0,937,0,0,937,0,0,0,0,0,0,0,0,0,0,0,...","12000,15576,4320,14400,12000,720,17844,15360,1...","150,0,0,0,0,0,0,0,0,0,0,0,50,0,0,0,0,0,0,0,0,0...","0,0,0,0,0,0,0,0,0,0,0,0,0,200,0,0,0,200,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,477,66,345,627,255,954,100,100,155,80,0,0,10..."
2,31815,1100031,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"Estaturaadequadaparaaidade,Estaturaadequadapar...","Sobrepeso,Eutrofia,Eutrofia,Eutrofia,Magreza,E...","1100031,1100031,1100031,1100031,1100031,110003...","3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,...",...,"E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,AUXILIOBRASIL,...",,"0,0,0,0,0,0,0,0,0,0,0,200,0,0,0,0,100,0,0,0,0,...","0,200,0,0,700,250,0,0,0,1500,0,0,1200,0,0,0,0,...","0,0,0,880,0,0,0,0,0,0,0,0,0,0,0,0,0,880,0,0,0,...","600,8400,3000,18000,14400,7800,4800,9456,6000,...","0,0,0,0,0,0,50,0,0,0,0,0,0,0,0,0,0,250,0,0,0,0...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","880,80,20,880,357,200,532,150,200,50,1908,954,..."
3,31820,1100049,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"Estaturaadequadaparaaidade,Estaturaadequadapar...","Riscodesobrepeso,Eutrofia,Eutrofia,Eutrofia,Eu...","1100049,1100049,1100049,1100049,1100049,110004...","3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,...",...,"E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSA...",,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,125,0,0,0,0,0,0,...","0,954,0,0,0,0,0,0,0,900,1874,0,1500,0,0,250,0,...","0,954,0,0,937,0,937,0,0,0,0,0,0,0,0,954,0,0,0,...","11448,10800,22488,18000,1380,10560,13032,6000,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,300,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","193,83,636,100,175,433,568,937,288,440,137,372..."
4,31825,1100056,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"Estaturaadequadaparaaidade,Estaturaadequadapar...","Eutrofia,Eutrofia,Eutrofia,Eutrofia,Eutrofia,E...","1100056,1100056,1100056,1100056,1100056,110005...","3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,...",...,"E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSA...",,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,954,0,0,0,0,200,400,0,0,0,900,0,200,0,0,1500...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,788,0,0,0,0,...","11448,2400,4800,10800,2400,18000,6000,11244,14...","0,0,0,0,100,250,0,0,0,0,200,0,0,0,0,0,0,0,0,0,...","150,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","160,300,468,60,83,477,937,150,1200,50,575,35,6..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,34030,1721208,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"Estaturaadequadaparaaidade,Estaturaadequadapar...","Magreza,Eutrofia,Eutrofia,Eutrofia,Riscodesobr...","1721208,1721208,1721208,1721208,1721208,172120...","3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,...",...,"E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSA...",,"100,600,100,0,0,700,0,0,0,0,0,0,0,0,0,70,0,0,0...","0,0,0,0,0,0,937,1365,0,0,0,0,0,0,0,0,0,937,0,0...","0,0,0,0,0,0,0,954,0,0,0,0,0,0,937,0,0,0,0,0,0,...","11244,16380,10784,2400,2400,6559,1000,13200,93...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,150,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","377,30,147,954,0,125,220,50,50,0,27,100,880,25..."
446,34035,1721257,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"Estaturaadequadaparaaidade,Estaturaadequadapar...","Eutrofia,Eutrofia,Riscodesobrepeso,Eutrofia,So...","1721257,1721257,1721257,1721257,1721257,172125...","3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,...",...,"E-SUSAB,E-SUSAB,AUXILIOBRASIL,E-SUSAB,E-SUSAB,...",,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,200,0,0,0,0,970,60,0,738,0,0,0,0,937,0...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","2400,11640,720,3690,1874,720,807,16344,3520,13...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","644,16,0,0,62,556,937,46,0,0,100,954,0,885,78,..."
447,34040,1721307,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"Estaturaadequadaparaaidade,Estaturaadequadapar...","Eutrofia,Eutrofia,Eutrofia,Riscodesobrepeso,Eu...","1721307,1721307,1721307,1721307,1721307,172130...","3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,...",...,"E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,AUXILI...",,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,50,0,0,0,0,200,0,1500,200,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,880,0,0,0,0,0,0,0,880,0,0,0,0,0,...","600,2400,18000,2400,2400,1000,2400,9306,11244,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","19,2,150,468,0,11,954,724,250,477,0,306,0,0,38..."
448,34045,1722081,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"Estaturaadequadaparaaidade,Estaturaadequadapar...","Eutrofia,Sobrepeso,Eutrofia,Eutrofia,Eutrofia,...","1722081,1722081,1722081,1722081,1722081,172208...","3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,...",...,"E-SUSAB,AUXILIOBRASIL,AUXILIOBRASIL,AUXILIOBRA...",,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,200,0,0,0,0,0,1149,200,0,0,0,100,0,0,0,0,1...","0,0,0,0,0,0,0,0,937,880,0,0,0,0,0,0,0,954,0,0,...","400,13788,2400,1400,1200,300,2000,3600,10556,1...","0,100,0,50,150,0,0,0,0,0,0,0,130,0,0,0,0,100,0...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","4,66,100,20,62,50,300,200,420,8,937,37,416,477..."
449,34050,1722107,NaN,2018,2018-01-01 00:00:00+00,2018-12-31 23:59:59.999+00,"Muitobaixaestaturaparaidade,Estaturaadequadapa...","Eutrofia,Eutrofia,Eutrofia,Riscodesobrepeso,Eu...","1722107,1722107,1722107,1722107,1722107,172210...","3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,...",...,"E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSAB,E-SUSA...",,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,120,0,0,600,0,500,150,1500,200,0,954,400,0,9...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,937,0,0,0,0,0,0,0,...","720,7200,6000,1800,6000,1800,11448,4800,11244,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,80...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","954,60,20,12,50,66,937,75,312,60,140,37,900,0,..."

In [ ]:
df.ST_PARTICIPA_ANDI

0
1
2
3
4
       ..
1186
1187
1188
1189
1190
Name: ST_PARTICIPA_ANDI, Length: 1191, dtype: object

## DS_IMC_PRE_GESTACIONAL

In [ ]:
# Check if there is any non-null content in the DS_IMC_PRE_GESTACIONAL column
has_content = df['DS_IMC_PRE_GESTACIONAL'].notna().any()

print(f"Does the 'DS_IMC_PRE_GESTACIONAL' column have any content (non-null values)? {has_content}")

# Count the number of non-null values
non_null_count = df['DS_IMC_PRE_GESTACIONAL'].notna().sum()
print(f"Number of non-null values in 'DS_IMC_PRE_GESTACIONAL': {non_null_count}")

# Count the number of rows with zero elements (empty strings after cleaning)
zero_elements_count = (df['DS_IMC_PRE_GESTACIONAL'] == '').sum()
print(f"Number of rows with zero elements in 'DS_IMC_PRE_GESTACIONAL': {zero_elements_count}")

Does the 'DS_IMC_PRE_GESTACIONAL' column have any content (non-null values)? True
Number of non-null values in 'DS_IMC_PRE_GESTACIONAL': 450
Number of rows with zero elements in 'DS_IMC_PRE_GESTACIONAL': 406

In [ ]:
# Filter out empty strings and count the elements in each non-empty row
element_counts = df['DS_IMC_PRE_GESTACIONAL'][df['DS_IMC_PRE_GESTACIONAL'] != ''].apply(lambda x: len(x.split(',')))

print("Counts of elements in non-empty rows of 'DS_IMC_PRE_GESTACIONAL':")
print(element_counts)

Counts of elements in non-empty rows of 'DS_IMC_PRE_GESTACIONAL':
20       1
74       1
75      15
103      1
126      6
132      3
151    107
154      1
166    158
168     15
171     11
174      2
177      3
182     14
185      3
189      1
191      1
197      6
205      3
213      6
219      5
221      1
225     73
227      3
233      5
237      2
241      1
244      5
247      8
248     53
251      6
253     20
270      2
278      1
281    977
287     13
288    146
290      1
294     17
303    238
368      3
414     57
425      1
443     24
Name: DS_IMC_PRE_GESTACIONAL, dtype: int64

## ST_PARTICIPA_ANDI

In [ ]:
# Check if there is any non-null content in the DS_IMC_PRE_GESTACIONAL column
has_content = df['ST_PARTICIPA_ANDI'].notna().any()

print(f"Does the 'ST_PARTICIPA_ANDI' column have any content (non-null values)? {has_content}")

# Count the number of non-null values
non_null_count = df['ST_PARTICIPA_ANDI'].notna().sum()
print(f"Number of non-null values in 'ST_PARTICIPA_ANDI': {non_null_count}")

# Count the number of rows with zero elements (empty strings after cleaning)
zero_elements_count = (df['ST_PARTICIPA_ANDI'] == '').sum()
print(f"Number of rows with zero elements in 'ST_PARTICIPA_ANDI': {zero_elements_count}")

Does the 'ST_PARTICIPA_ANDI' column have any content (non-null values)? True
Number of non-null values in 'ST_PARTICIPA_ANDI': 450
Number of rows with zero elements in 'ST_PARTICIPA_ANDI': 450

In [ ]:
# Filter out empty strings and count the elements in each non-empty row
element_counts = df['ST_PARTICIPA_ANDI'][df['ST_PARTICIPA_ANDI'] != ''].apply(lambda x: len(x.split(',')))

print("Counts of elements in non-empty rows of 'ST_PARTICIPA_ANDI':")
print(element_counts)

Counts of elements in non-empty rows of 'ST_PARTICIPA_ANDI':
Series([], Name: ST_PARTICIPA_ANDI, dtype: object)

## CO_POVO_COMUNIDADE

In [ ]:
# Check if there is any non-null content in the DS_IMC_PRE_GESTACIONAL column
has_content = df['CO_POVO_COMUNIDADE'].notna().any()

print(f"Does the 'CO_POVO_COMUNIDADE' column have any content (non-null values)? {has_content}")

# Count the number of non-null values
non_null_count = df['CO_POVO_COMUNIDADE'].notna().sum()
print(f"Number of non-null values in 'CO_POVO_COMUNIDADE': {non_null_count}")

# Count the number of rows with zero elements (empty strings after cleaning)
zero_elements_count = (df['CO_POVO_COMUNIDADE'] == '').sum()
print(f"Number of rows with zero elements in 'CO_POVO_COMUNIDADE': {zero_elements_count}")

Does the 'CO_POVO_COMUNIDADE' column have any content (non-null values)? True
Number of non-null values in 'CO_POVO_COMUNIDADE': 450
Number of rows with zero elements in 'CO_POVO_COMUNIDADE': 88

In [ ]:
# Filter out empty strings and count the elements in each non-empty row
element_counts = df['ST_PARTICIPA_ANDI'][df['CO_POVO_COMUNIDADE'] != ''].apply(lambda x: len(x.split(',')))

print("Counts of elements in non-empty rows of 'CO_POVO_COMUNIDADE':")
print(element_counts)

Counts of elements in non-empty rows of 'CO_POVO_COMUNIDADE':
1      1
3      1
8      1
10     1
11     1
      ..
445    1
446    1
447    1
448    1
449    1
Name: ST_PARTICIPA_ANDI, Length: 362, dtype: int64

## CO_ESTADO_NUTRI_IMC_SEMGEST

In [ ]:
# Check if there is any non-null content in the DS_IMC_PRE_GESTACIONAL column
has_content = df['CO_ESTADO_NUTRI_IMC_SEMGEST'].notna().any()

print(f"Does the 'CO_ESTADO_NUTRI_IMC_SEMGEST' column have any content (non-null values)? {has_content}")

# Count the number of non-null values
non_null_count = df['CO_ESTADO_NUTRI_IMC_SEMGEST'].notna().sum()
print(f"Number of non-null values in 'CO_ESTADO_NUTRI_IMC_SEMGEST': {non_null_count}")

# Count the number of rows with zero elements (empty strings after cleaning)
zero_elements_count = (df['CO_ESTADO_NUTRI_IMC_SEMGEST'] == '').sum()
print(f"Number of rows with zero elements in 'CO_ESTADO_NUTRI_IMC_SEMGEST': {zero_elements_count}")

Does the 'CO_ESTADO_NUTRI_IMC_SEMGEST' column have any content (non-null values)? True
Number of non-null values in 'CO_ESTADO_NUTRI_IMC_SEMGEST': 450
Number of rows with zero elements in 'CO_ESTADO_NUTRI_IMC_SEMGEST': 2

In [ ]:
# Filter out empty strings and count the elements in each non-empty row
element_counts = df['CO_ESTADO_NUTRI_IMC_SEMGEST'][df['CO_ESTADO_NUTRI_IMC_SEMGEST'] != ''].apply(lambda x: len(x.split(',')))

print("Counts of elements in non-empty rows of 'CO_ESTADO_NUTRI_IMC_SEMGEST':")
print(element_counts)

Counts of elements in non-empty rows of 'CO_ESTADO_NUTRI_IMC_SEMGEST':
0       10
1       54
2        8
3      184
4        6
      ...
445     44
446      1
447      4
448     20
449     24
Name: CO_ESTADO_NUTRI_IMC_SEMGEST, Length: 448, dtype: int64

## qtd_comodos_domic_fam

In [ ]:
# Check if there is any non-null content in the DS_IMC_PRE_GESTACIONAL column
has_content = df['qtd_comodos_domic_fam'].notna().any()

print(f"Does the 'qtd_comodos_domic_fam' column have any content (non-null values)? {has_content}")

# Count the number of non-null values
non_null_count = df['qtd_comodos_domic_fam'].notna().sum()
print(f"Number of non-null values in 'qtd_comodos_domic_fam': {non_null_count}")

# Count the number of rows with zero elements (empty strings after cleaning)
zero_elements_count = (df['qtd_comodos_domic_fam'] == '').sum()
print(f"Number of rows with zero elements in 'qtd_comodos_domic_fam': {zero_elements_count}")

Does the 'qtd_comodos_domic_fam' column have any content (non-null values)? True
Number of non-null values in 'qtd_comodos_domic_fam': 446
Number of rows with zero elements in 'qtd_comodos_domic_fam': 0

In [ ]:
# Filter out empty strings and count the elements in each non-empty row
element_counts = df['qtd_comodos_domic_fam'][df['qtd_comodos_domic_fam'] != ''].apply(lambda x: len(x.split(',')))

print("Counts of elements in non-empty rows of 'qtd_comodos_domic_fam':")
print(element_counts)

AttributeError: 'float' object has no attribute 'split'

## qtde_pessoas

In [ ]:
# Check if there is any non-null content in the DS_IMC_PRE_GESTACIONAL column
has_content = df['qtde_pessoas'].notna().any()

print(f"Does the 'qtde_pessoas' column have any content (non-null values)? {has_content}")

# Count the number of non-null values
non_null_count = df['qtde_pessoas'].notna().sum()
print(f"Number of non-null values in 'qtde_pessoas': {non_null_count}")

# Count the number of rows with zero elements (empty strings after cleaning)
zero_elements_count = (df['qtde_pessoas'] == '').sum()
print(f"Number of rows with zero elements in 'qtde_pessoas': {zero_elements_count}")

Does the 'qtde_pessoas' column have any content (non-null values)? True
Number of non-null values in 'qtde_pessoas': 446
Number of rows with zero elements in 'qtde_pessoas': 0

In [ ]:
# Filter out empty strings and count the elements in each non-empty row
element_counts = df['qtd_comodos_domic_fam'][df['qtd_comodos_domic_fam'] != ''].apply(lambda x: len(x.split(',')))

print("Counts of elements in non-empty rows of 'qtd_comodos_domic_fam':")
print(element_counts)

AttributeError: 'float' object has no attribute 'split'

## cod_sexo_pessoa

In [ ]:
has_content = df['cod_sexo_pessoa'].notna().any()

print(f"Does the 'cod_sexo_pessoa' column have any content (non-null values)? {has_content}")

# Count the number of non-null values
non_null_count = df['cod_sexo_pessoa'].notna().sum()
print(f"Number of non-null values in 'cod_sexo_pessoa': {non_null_count}")

# Count the number of rows with zero elements (empty strings after cleaning)
zero_elements_count = (df['cod_sexo_pessoa'] == '').sum()
print(f"Number of rows with zero elements in 'cod_sexo_pessoa': {zero_elements_count}")

Does the 'cod_sexo_pessoa' column have any content (non-null values)? True
Number of non-null values in 'cod_sexo_pessoa': 450
Number of rows with zero elements in 'cod_sexo_pessoa': 0

In [ ]:
# Filter out empty strings and count the elements in each non-empty row
element_counts = df['cod_sexo_pessoa'][df['cod_sexo_pessoa'] != ''].apply(lambda x: len(x.split(',')))

print("Counts of elements in non-empty rows of 'cod_sexo_pessoa':")
print(element_counts)

## marc_pbf

In [ ]:
has_content = df['marc_pbf'].notna().any()

print(f"Does the 'marc_pbf' column have any content (non-null values)? {has_content}")

# Count the number of non-null values
non_null_count = df['marc_pbf'].notna().sum()
print(f"Number of non-null values in 'marc_pbf': {non_null_count}")

# Count the number of rows with zero elements (empty strings after cleaning)
zero_elements_count = (df['marc_pbf'] == '').sum()
print(f"Number of rows with zero elements in 'marc_pbf': {zero_elements_count}")

Does the 'marc_pbf' column have any content (non-null values)? True
Number of non-null values in 'marc_pbf': 446
Number of rows with zero elements in 'marc_pbf': 0

In [ ]:
# Filter out empty strings and count the elements in each non-empty row
element_counts = df['marc_pbf'][df['marc_pbf'] != ''].apply(lambda x: len(x.split(',')))

print("Counts of elements in non-empty rows of 'marc_pbf':")
print(element_counts)

## val_outras_rendas_memb

In [ ]:
has_content = df['val_outras_rendas_memb'].notna().any()

print(f"Does the 'val_outras_rendas_memb' column have any content (non-null values)? {has_content}")

# Count the number of non-null values
non_null_count = df['val_outras_rendas_memb'].notna().sum()
print(f"Number of non-null values in 'val_outras_rendas_memb': {non_null_count}")

# Count the number of rows with zero elements (empty strings after cleaning)
zero_elements_count = (df['val_outras_rendas_memb'] == '').sum()
print(f"Number of rows with zero elements in 'val_outras_rendas_memb': {zero_elements_count}")

Does the 'val_outras_rendas_memb' column have any content (non-null values)? True
Number of non-null values in 'val_outras_rendas_memb': 450
Number of rows with zero elements in 'val_outras_rendas_memb': 0

In [ ]:
# Filter out empty strings and count the elements in each non-empty row
element_counts = df['val_outras_rendas_memb'][df['val_outras_rendas_memb'] != ''].apply(lambda x: len(x.split(',')))

print("Counts of elements in non-empty rows of 'val_outras_rendas_memb':")
print(element_counts)

## val_renda_seguro_desemp_memb

In [ ]:
has_content = df['val_renda_seguro_desemp_memb'].notna().any()

print(f"Does the 'val_renda_seguro_desemp_memb' column have any content (non-null values)? {has_content}")

# Count the number of non-null values
non_null_count = df['val_renda_seguro_desemp_memb'].notna().sum()
print(f"Number of non-null values in 'val_renda_seguro_desemp_memb': {non_null_count}")

# Count the number of rows with zero elements (empty strings after cleaning)
zero_elements_count = (df['val_renda_seguro_desemp_memb'] == '').sum()
print(f"Number of rows with zero elements in 'val_renda_seguro_desemp_memb': {zero_elements_count}")

Does the 'val_renda_seguro_desemp_memb' column have any content (non-null values)? True
Number of non-null values in 'val_renda_seguro_desemp_memb': 450
Number of rows with zero elements in 'val_renda_seguro_desemp_memb': 0

In [ ]:
# Filter out empty strings and count the elements in each non-empty row
element_counts = df['val_renda_seguro_desemp_memb'][df['val_renda_seguro_desemp_memb'] != ''].apply(lambda x: len(x.split(',')))

print("Counts of elements in non-empty rows of 'val_renda_seguro_desemp_memb':")
print(element_counts)

## val_renda_doacao_memb

In [ ]:
has_content = df['val_renda_doacao_memb'].notna().any()

print(f"Does the 'val_renda_doacao_memb' column have any content (non-null values)? {has_content}")

# Count the number of non-null values
non_null_count = df['val_renda_doacao_memb'].notna().sum()
print(f"Number of non-null values in 'val_renda_doacao_memb': {non_null_count}")

# Count the number of rows with zero elements (empty strings after cleaning)
zero_elements_count = (df['val_renda_doacao_memb'] == '').sum()
print(f"Number of rows with zero elements in 'val_renda_doacao_memb': {zero_elements_count}")

Does the 'val_renda_doacao_memb' column have any content (non-null values)? True
Number of non-null values in 'val_renda_doacao_memb': 450
Number of rows with zero elements in 'val_renda_doacao_memb': 0

In [ ]:
# Filter out empty strings and count the elements in each non-empty row
element_counts = df['val_renda_doacao_memb'][df['val_renda_doacao_memb'] != ''].apply(lambda x: len(x.split(',')))

print("Counts of elements in non-empty rows of 'val_renda_doacao_memb':")
print(element_counts)